/*
 * Copyright 2026 Senfoni Authors
 *
 * This file is part of NetSurf, http://www.netsurf-browser.org/
 *
 * NetSurf is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 2 of the License.
 *
 * NetSurf is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * \file
 * QuickJS implementation of the js.h interface for NetSurf.
 *
 * Phase 2 core + Phase 5 DOM/event completion.
 *   - jsheap / jsthread lifecycle
 *   - js_exec() with execution timeout
 *   - polyfill.js + generics.js embedded and run on thread creation
 *   - js_fire_event, js_handle_new_element, js_event_cleanup via qjsw_helpers
 *
 * Selected at build time via NETSURF_USE_QUICKJS=YES (see javascript/Makefile).
 */

#ifndef QJSCORE_TEST_BUILD
/* Normal NetSurf build — include the real headers */
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <assert.h>

#include "utils/errors.h"
#include "utils/log.h"
#include "utils/nsoption.h"
#include "utils/corestrings.h"
#include "content/content.h"
#include "javascript/js.h"
#include "javascript/content.h"

#include <dom/dom.h>
#else
/* Test build — stub headers are provided by the test file before #include */
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <assert.h>

/* Provide the opaque typedefs that js.h normally supplies */
typedef struct jsheap   jsheap;
typedef struct jsthread jsthread;
#endif

#include "quickjs/quickjs.h"
#ifndef QJSCORE_TEST_BUILD
#include "qjs_binding.h"
#include "qjsw_helpers.h"
#include "build/Linux-framebuffer/quickjs/private.h"

/* Use jserrors category at WARNING level — guaranteed to pass NSLOG filter
 * which is "(level:WARNING || cat:jserrors)". */
#define ALOG_QJS(fmt, ...) NSLOG(jserrors, WARNING, "QJS: " fmt, ##__VA_ARGS__)
#else
#define ALOG_QJS(...) ((void)0)
#endif

/* Embedded polyfill.js and generics.js byte arrays.
 * In a NetSurf build these come from $(OBJROOT)/quickjs/polyfill.js.inc and
 * generics.js.inc, generated by the quickjs/Makefile via xxd.
 * In a test build the test sets up OBJROOT_QUICKJS_INC_PATH so they resolve. */
#include "quickjs/polyfill.js.inc"
#include "quickjs/generics.js.inc"

/* ── Internal stash property names ──────────────────────────────────────────
 * These are stored as plain string properties on the JS global object.
 * Duktape used \xFF\xFF hidden properties; QuickJS has no equivalent so we
 * use printable but unlikely-to-clash names.                                  */
#define QJS_NODE_MAP     "__NSQJS_NODE_MAP__"
#define QJS_EVENT_MAP    "__NSQJS_EVENT_MAP__"
#define QJS_PROTO_MAP    "__NSQJS_PROTO_MAP__"
#define QJS_GENERICS     "__NSQJS_GENERICS__"
#define QJS_HANDLER_MAP  "__NSQJS_HANDLER_MAP__"

/* Execution timeout: 10 seconds (matches original JS_EXEC_TIMEOUT_MS=10000) */
#define JS_EXEC_TIMEOUT_NS (10ULL * 1000000000ULL)

/* ── Heap ──────────────────────────────────────────────────────────────────── */
struct jsheap {
	JSRuntime      *rt;
	int             timeout_secs;
	bool            pending_destroy;
	unsigned int    live_threads;
	struct timespec exec_start;   /**< monotonic clock at start of js_exec */
	bool            exec_timing;  /**< true while exec_start is valid */
	unsigned int    exec_count;   /**< total js_exec calls (for periodic GC/logging) */
};

/* ── Thread ────────────────────────────────────────────────────────────────── */
struct jsthread {
	JSContext    *ctx;
	jsheap       *heap;
	bool          pending_destroy;
	unsigned int  in_use;
};

/* ── Forward declarations for jsthread access from ctx ───────────────────── */

static jsthread *qjs_thread_from_ctx(JSContext *ctx)
{
	return (jsthread *)JS_GetContextOpaque(ctx);
}

/* ── Interrupt handler (execution timeout) ───────────────────────────────── */

static int qjs_interrupt_handler(JSRuntime *rt, void *opaque)
{
	(void)rt;
	jsheap *heap = (jsheap *)opaque;

	if (!heap->exec_timing)
		return 0;

	struct timespec now;
	clock_gettime(CLOCK_MONOTONIC, &now);

	uint64_t elapsed_ns =
		(uint64_t)(now.tv_sec  - heap->exec_start.tv_sec)  * 1000000000ULL +
		(uint64_t)(now.tv_nsec - heap->exec_start.tv_nsec);

	if (elapsed_ns > JS_EXEC_TIMEOUT_NS) {
		NSLOG(jserrors, WARNING, "QuickJS: execution timeout after ~10s");
		return 1; /* non-zero interrupts execution */
	}
	return 0;
}

static void qjs_reset_exec_timer(jsheap *heap)
{
	clock_gettime(CLOCK_MONOTONIC, &heap->exec_start);
	heap->exec_timing = true;
}

/* ── Exported timer reset — called from qjsw_helpers.c ──────────────────── */

void qjs_reset_exec_timer_from_ctx(JSContext *ctx)
{
	jsthread *t = qjs_thread_from_ctx(ctx);
	if (t != NULL)
		qjs_reset_exec_timer(t->heap);
}

/* ── Error logging helper ────────────────────────────────────────────────── */

static void qjs_log_exception(JSContext *ctx)
{
	JSValue exc = JS_GetException(ctx);
	if (!JS_IsNull(exc) && !JS_IsUndefined(exc)) {
		/* Print error message */
		const char *msg = JS_ToCString(ctx, exc);
		NSLOG(jserrors, WARNING, "QuickJS exception: %s",
		      msg ? msg : "(unknown)");
		JS_FreeCString(ctx, msg);
		/* Also print stack trace if available */
		JSValue stk = JS_GetPropertyStr(ctx, exc, "stack");
		if (!JS_IsUndefined(stk)) {
			const char *s = JS_ToCString(ctx, stk);
			NSLOG(jserrors, WARNING, "  stack: %s",
			      s ? s : "(no stack)");
			JS_FreeCString(ctx, s);
		}
		JS_FreeValue(ctx, stk);
	}
	JS_FreeValue(ctx, exc);
}

/* ── JS_DeletePropertyStr helper (not in public API before 2023) ─────────── */

static void qjs_delete_global_prop(JSContext *ctx, const char *name)
{
	JSValue global = JS_GetGlobalObject(ctx);
	JSAtom atom = JS_NewAtom(ctx, name);
	JS_DeleteProperty(ctx, global, atom, 0);
	JS_FreeAtom(ctx, atom);
	JS_FreeValue(ctx, global);
}

/* ── Embed helper: eval a byte-array script ──────────────────────────────── */

static bool qjs_eval_bytes(JSContext *ctx,
			    const unsigned char *src, unsigned int src_len,
			    const char *filename)
{
	JSValue val = JS_Eval(ctx, (const char *)src, src_len, filename,
			      JS_EVAL_TYPE_GLOBAL);
	if (JS_IsException(val)) {
		qjs_log_exception(ctx);
		JS_FreeValue(ctx, val);
		return false;
	}
	JS_FreeValue(ctx, val);
	return true;
}

/* ══════════════════════════════════════════════════════════════════════════
 * Heap lifecycle — documented in js.h
 * ══════════════════════════════════════════════════════════════════════════ */

void js_initialise(void)
{
	javascript_init();
}

void js_finalise(void)
{
	/* nothing */
}

nserror js_newheap(int timeout, jsheap **heap)
{
	jsheap *h = calloc(1, sizeof(*h));
	if (h == NULL)
		return NSERROR_NOMEM;

	h->timeout_secs = timeout;
	h->rt = JS_NewRuntime();
	if (h->rt == NULL) {
		free(h);
		return NSERROR_NOMEM;
	}

	/* Wire timeout interrupt handler */
	JS_SetInterruptHandler(h->rt, qjs_interrupt_handler, h);

	/* Cap memory at 256 MB (generous for the Sony NSX Atom CE4170) */
	JS_SetMemoryLimit(h->rt, 256 * 1024 * 1024);

	*heap = h;
	NSLOG(quickjs, DEBUG, "QuickJS: heap created (rt=%p)", (void *)h->rt);
	ALOG_QJS("heap created (rt=%p, memlimit=256MB)", (void *)h->rt);
	return NSERROR_OK;
}

static void qjs_destroyheap(jsheap *heap)
{
	assert(heap->pending_destroy);
	assert(heap->live_threads == 0);
	NSLOG(quickjs, DEBUG, "QuickJS: heap destroyed (rt=%p)", (void *)heap->rt);
	JS_FreeRuntime(heap->rt);
	free(heap);
}

void js_destroyheap(jsheap *heap)
{
	if (heap == NULL)
		return;
	heap->pending_destroy = true;
	if (heap->live_threads == 0)
		qjs_destroyheap(heap);
}

/* ══════════════════════════════════════════════════════════════════════════
 * Thread lifecycle — documented in js.h
 * ══════════════════════════════════════════════════════════════════════════ */

static void qjs_destroythread(jsthread *thread); /* forward — defined below */
void js_destroythread(jsthread *thread);          /* forward — used in js_newthread error path */

static void qjs_enter_thread(jsthread *t)
{
	assert(t != NULL);
	t->in_use++;
}

static void qjs_leave_thread(jsthread *t)
{
	assert(t != NULL);
	assert(t->in_use > 0);
	t->in_use--;
	if (t->in_use == 0 && t->pending_destroy)
		qjs_destroythread(t);
}

nserror js_newthread(jsheap *heap, void *win_priv, void *doc_priv,
		     jsthread **thread)
{
	assert(heap != NULL);
	assert(!heap->pending_destroy);

	jsthread *t = calloc(1, sizeof(*t));
	if (t == NULL)
		return NSERROR_NOMEM;

	t->heap = heap;
	t->ctx  = JS_NewContext(heap->rt);
	if (t->ctx == NULL) {
		free(t);
		return NSERROR_NOMEM;
	}

	heap->live_threads++;

	/* Clear any stale execution timer from a previous thread's event
	 * handler (js_fire_event sets exec_timing but may not clear it). */
	heap->exec_timing = false;

	/* Store back-pointer so qjs_thread_from_ctx() works */
	JS_SetContextOpaque(t->ctx, t);

	JSContext *ctx    = t->ctx;
	JSValue    global = JS_GetGlobalObject(ctx);

	/* Phase 2: stash win_priv/doc_priv as integer properties.
	 * Phase 3 will replace this with a proper Window prototype. */
	JS_SetPropertyStr(ctx, global, "__win_priv__",
			  JS_NewInt64(ctx, (int64_t)(uintptr_t)win_priv));
	JS_SetPropertyStr(ctx, global, "__doc_priv__",
			  JS_NewInt64(ctx, (int64_t)(uintptr_t)doc_priv));

	/* Internal maps — will hold node/event/handler JS wrappers */
	JS_SetPropertyStr(ctx, global, QJS_NODE_MAP,    JS_NewObject(ctx));
	JS_SetPropertyStr(ctx, global, QJS_EVENT_MAP,   JS_NewObject(ctx));
	JS_SetPropertyStr(ctx, global, QJS_HANDLER_MAP, JS_NewObject(ctx));
	JS_SetPropertyStr(ctx, global, QJS_PROTO_MAP,   JS_NewObject(ctx));

	JS_FreeValue(ctx, global);

#ifndef QJSCORE_TEST_BUILD
	/* Register all DOM binding classes and prototypes.
	 * Declared in generated binding.h; forward-declare here to avoid
	 * pulling in all 198 class ID externs. */
	{
		extern void qjsw_create_prototypes(JSContext *ctx);
		extern JSClassID window_class_id;
		qjsw_create_prototypes(ctx);

		/* Add DOM3 localName/namespaceURI/prefix to Node proto */
		qjsw_patch_node_proto_dom3(ctx);

		/* Wire up the global object as a Window instance.
		 * In Duktape this is done via duk_set_global_object();
		 * QuickJS has no equivalent, so we set the global's
		 * prototype chain and store window_private_t as a
		 * stash property (since JS_SetOpaque only works on
		 * objects created with a specific class_id). */
		/* Wire up the global object as a Window instance.
		 * Store htmlc/win pointers and set proto chain. */
		JSValue g = JS_GetGlobalObject(ctx);
		JSValue win_proto = JS_GetClassProto(ctx, window_class_id);
		JS_SetPrototype(ctx, g, win_proto);
		JS_FreeValue(ctx, win_proto);

		/* Allocate window_private_t and store as stash property
		 * so Window getters (document, location, etc.) can find it. */
		{
			window_private_t *wp = calloc(1, sizeof(*wp));
			if (wp != NULL) {
				wp->htmlc = (struct html_content *)doc_priv;
				wp->win   = (struct browser_window *)win_priv;
				JS_SetPropertyStr(ctx, g,
					"__NSQJS_WIN_PRIV__",
					JS_NewInt64(ctx,
						(int64_t)(uintptr_t)wp));
			}
		}
		JS_FreeValue(ctx, g);
	}
#endif

	qjsw_reset_generics_state();

	/* Run polyfill.js — adds missing ES features for Duktape compat.
	 * QuickJS is ES2020 so most polyfills are no-ops; we run it anyway
	 * for compatibility with future .bnd-generated code.
	 * NOTE: In Phase 2 (no DOM bindings) some polyfills reference
	 * DOMTokenList etc. which are undefined — failure is non-fatal. */
	if (!qjs_eval_bytes(ctx, polyfill_js, polyfill_js_len, "polyfill.js")) {
		NSLOG(quickjs, WARNING,
		      "QuickJS: polyfill.js had errors (expected in Phase 2 "
		      "before DOM bindings); continuing");
	}

	/* Run generics.js — result must place a NetSurf object on global.
	 * We then absorb it into the GENERICS stash and hide it.
	 * Also non-fatal in Phase 2 if DOM symbols are missing.
	 *
	 * IMPORTANT: When generics.js fails (e.g. on 32-bit Android API 13),
	 * do NOT access global properties afterwards — the failed eval can
	 * leave the QuickJS global object property table in a state that
	 * causes SIGSEGV on subsequent JS_GetPropertyStr calls. */
	if (qjs_eval_bytes(ctx, generics_js, generics_js_len, "generics.js")) {
		/* Absorb NetSurf object into private stash, remove from global */
		JSValue g2    = JS_GetGlobalObject(ctx);
		JSValue ns_ob = JS_GetPropertyStr(ctx, g2, "NetSurf");
		if (!JS_IsUndefined(ns_ob) && !JS_IsException(ns_ob))
			JS_SetPropertyStr(ctx, g2, QJS_GENERICS,
					  JS_DupValue(ctx, ns_ob));
		JS_FreeValue(ctx, ns_ob);
		qjs_delete_global_prop(ctx, "NetSurf");
		JS_FreeValue(ctx, g2);
	} else {
		NSLOG(quickjs, WARNING,
		      "QuickJS: generics.js had errors (expected in Phase 2); "
		      "NetSurf generics unavailable");
	}

	/* Patch document with traversal/range polyfills via JS_Eval.
	 * The auto-gen stubs for createRange/createNodeIterator/createTreeWalker
	 * have a priv-null check that returns undefined. We override them by
	 * defining the methods directly on the document object (own property
	 * shadows prototype method). */
	{
		/* Polyfill.js defines Range/NodeIterator/TreeWalker but they
		 * end up on the eval scope's `this`, not on the Window global
		 * that page scripts see. Use JS_Eval with globalThis to
		 * bridge them, then install create* on document prototype. */
		static const char patch_src[] =
			"(function() {"
			"  var g = globalThis;"
			"  if (typeof Range !== 'undefined') g.Range = Range;"
			"  if (typeof NodeIterator !== 'undefined') g.NodeIterator = NodeIterator;"
			"  if (typeof TreeWalker !== 'undefined') g.TreeWalker = TreeWalker;"
			"  if (typeof DOMException !== 'undefined') g.DOMException = DOMException;"
			"  if (typeof NodeFilter !== 'undefined') g.NodeFilter = NodeFilter;"
			"  var d = document;"
			"  if (!d) return 'no-doc';"
			"  var p = Object.getPrototypeOf(d);"
			"  if (!p) return 'no-proto';"
			"  if (typeof Range === 'function') {"
			"    p.createRange = function() {"
			"      var r = new Range();"
			"      r.startContainer = this;"
			"      r.startOffset = 0;"
			"      r.endContainer = this;"
			"      r.endOffset = 0;"
			"      r.collapsed = true;"
			"      r.commonAncestorContainer = this;"
			"      return r;"
			"    };"
			"  }"
			"  if (typeof NodeIterator === 'function') {"
			"    p.createNodeIterator = function(root, ws, f) {"
			"      return new NodeIterator(root, ws, f);"
			"    };"
			"  }"
			"  if (typeof TreeWalker === 'function') {"
			"    p.createTreeWalker = function(root, ws, f) {"
			"      return new TreeWalker(root, ws, f);"
			"    };"
			"  }"
			""
			"  /* Patch iframe.contentDocument — native getter returns the"
			"   * real loaded document when available (via box->iframe)."
			"   * Fall back to a fake empty document for dynamically"
			"   * created iframes that have no box tree entry. */"
			"  try {"
			"    var ifr = d.createElement('iframe');"
			"    var ip = Object.getPrototypeOf(ifr);"
			"    if (ip) {"
			"      var nativeCD = Object.getOwnPropertyDescriptor(ip, 'contentDocument');"
			"      var nativeCDGet = nativeCD && nativeCD.get ? nativeCD.get : null;"
			"      delete ip.contentDocument;"
			"      Object.defineProperty(ip, 'contentDocument', {"
			"        get: function() {"
			"          if (nativeCDGet) {"
			"            var real = nativeCDGet.call(this);"
			"            if (real) return real;"
			"          }"
			"          if (!this.__cd) {"
			"            try { this.__cd = d.implementation.createHTMLDocument(''); }"
			"            catch(e) { return null; }"
			"            this.__cd.__frameElement = this;"
			"          }"
			"          return this.__cd;"
			"        },"
			"        configurable: true"
			"      });"
			"      Object.defineProperty(ip, 'contentWindow', {"
			"        get: function() {"
			"          var cd = this.contentDocument;"
			"          if (!cd) return null;"
			"          return cd.defaultView || {document: cd};"
			"        },"
			"        configurable: true"
			"      });"
			"    }"
			"  } catch(e) {}"
			/* object/embed contentDocument: skip for now — fake documents
			 * break test 73 (createEvent not available on fake docs) */
			"  /* Patch Text.splitText — native stub returns"
			"   * undefined. Override with JS implementation. */"
			"  try {"
			"    var tn = d.createTextNode('test');"
			"    var tp = Object.getPrototypeOf(tn);"
			"    if (tp) {"
			"      tp.splitText = function(offset) {"
			"        var newData = this.data.substring(offset);"
			"        this.data = this.data.substring(0, offset);"
			"        var newNode = this.ownerDocument.createTextNode(newData);"
			"        if (this.parentNode) {"
			"          this.parentNode.insertBefore(newNode, this.nextSibling);"
			"        }"
			"        return newNode;"
			"      };"
			"    }"
			"  } catch(e) {}"
			/* A4: table.tHead/tFoot/caption/tBodies polyfill */
			"  try {"
			"    var tbl = d.createElement('table');"
			"    var tbp = Object.getPrototypeOf(tbl);"
			"    if (tbp) {"
			"      function tblFind(t,tag) {"
			"        for(var c=t.firstChild;c;c=c.nextSibling)"
			"          if(c.nodeType===1&&c.tagName===tag) return c;"
			"        return null;"
			"      }"
			"      function tblFindAll(t,tag) {"
			"        var r=[];"
			"        for(var c=t.firstChild;c;c=c.nextSibling)"
			"          if(c.nodeType===1&&c.tagName===tag) r.push(c);"
			"        return r;"
			"      }"
			"      function tblRows(t) {"
			"        var r=[];"
			"        var th=tblFind(t,'THEAD');"
			"        if(th) for(var c=th.firstChild;c;c=c.nextSibling)"
			"          if(c.nodeType===1&&c.tagName==='TR') r.push(c);"
			"        var tbs=tblFindAll(t,'TBODY');"
			"        for(var i=0;i<tbs.length;i++)"
			"          for(var c=tbs[i].firstChild;c;c=c.nextSibling)"
			"            if(c.nodeType===1&&c.tagName==='TR') r.push(c);"
			"        var tf=tblFind(t,'TFOOT');"
			"        if(tf) for(var c=tf.firstChild;c;c=c.nextSibling)"
			"          if(c.nodeType===1&&c.tagName==='TR') r.push(c);"
			"        for(var c=t.firstChild;c;c=c.nextSibling)"
			"          if(c.nodeType===1&&c.tagName==='TR') r.push(c);"
			"        return r;"
			"      }"
			"      function tblSet(t,tag,val) {"
			"        var old = tblFind(t,tag);"
			"        if (val) {"
			"          if (val.tagName !== tag) throw new TypeError('wrong element type');"
			"          if (old && old !== val) t.replaceChild(val, old);"
			"          else if (!old) t.insertBefore(val, t.firstChild);"
			"        } else if (old) {"
			"          t.removeChild(old);"
			"        }"
			"      }"
			"      function tblCreate(t,tag) {"
			"        var ex = tblFind(t,tag);"
			"        if (ex) return ex;"
			"        var el = (t.ownerDocument||d).createElement(tag.toLowerCase());"
			"        if (tag==='CAPTION') {"
			"          t.insertBefore(el, t.firstChild);"
			"        } else if (tag==='THEAD') {"
			"          var ref = tblFind(t,'CAPTION');"
			"          t.insertBefore(el, ref ? ref.nextSibling : t.firstChild);"
			"        } else if (tag==='TFOOT') {"
			"          t.appendChild(el);"
			"        }"
			"        return el;"
			"      }"
			"      function tblDelete(t,tag) {"
			"        var el = tblFind(t,tag);"
			"        if (el) t.removeChild(el);"
			"      }"
			"      try{delete tbp.tHead;}catch(e){}"
			"      Object.defineProperty(tbp,'tHead',{"
			"        get:function(){return tblFind(this,'THEAD');},"
			"        set:function(v){tblSet(this,'THEAD',v);},"
			"        configurable:true"
			"      });"
			"      try{delete tbp.tFoot;}catch(e){}"
			"      Object.defineProperty(tbp,'tFoot',{"
			"        get:function(){return tblFind(this,'TFOOT');},"
			"        set:function(v){tblSet(this,'TFOOT',v);},"
			"        configurable:true"
			"      });"
			"      try{delete tbp.caption;}catch(e){}"
			"      Object.defineProperty(tbp,'caption',{"
			"        get:function(){return tblFind(this,'CAPTION');},"
			"        set:function(v){tblSet(this,'CAPTION',v);},"
			"        configurable:true"
			"      });"
			"      try{delete tbp.tBodies;}catch(e){}"
			"      Object.defineProperty(tbp,'tBodies',{get:function(){return tblFindAll(this,'TBODY');},configurable:true});"
			"      try{delete tbp.rows;}catch(e){}"
			"      Object.defineProperty(tbp,'rows',{get:function(){return tblRows(this);},configurable:true});"
			"      if(!tbp.createCaption)tbp.createCaption = function(){return tblCreate(this,'CAPTION');};"
			"      if(!tbp.createTHead)tbp.createTHead = function(){return tblCreate(this,'THEAD');};"
			"      if(!tbp.createTFoot)tbp.createTFoot = function(){return tblCreate(this,'TFOOT');};"
			"      if(!tbp.deleteCaption)tbp.deleteCaption = function(){tblDelete(this,'CAPTION');};"
			"      if(!tbp.deleteTHead)tbp.deleteTHead = function(){tblDelete(this,'THEAD');};"
			"      if(!tbp.deleteTFoot)tbp.deleteTFoot = function(){tblDelete(this,'TFOOT');};"
			"      if (!tbp.insertRow) {"
			"        tbp.insertRow = function(idx) {"
			"          var tb = tblFindAll(this,'TBODY');"
			"          if (!tb.length) {"
			"            var tbody = (this.ownerDocument||d).createElement('tbody');"
			"            this.appendChild(tbody);"
			"            tb = [tbody];"
			"          }"
			"          var tr = (this.ownerDocument||d).createElement('tr');"
			"          if (idx === undefined || idx === -1 || idx >= tblRows(this).length) {"
			"            tb[tb.length-1].appendChild(tr);"
			"          } else {"
			"            var rows = tblRows(this);"
			"            if (idx >= 0 && idx < rows.length) {"
			"              rows[idx].parentNode.insertBefore(tr, rows[idx]);"
			"            }"
			"          }"
			"          return tr;"
			"        };"
			"      }"
			"    }"
			"  } catch(e) {}"
			/* Polyfill HTMLTableSectionElement.rows and insertRow */
			"  try {"
			"    var tsec = d.createElement('tbody');"
			"    var tsp = Object.getPrototypeOf(tsec);"
			"    if (tsp) {"
			"      var origSecRows = null;"
			"      try{origSecRows=Object.getOwnPropertyDescriptor(tsp,'rows');}catch(e){}"
			"      if (!origSecRows || origSecRows.configurable !== false) {"
			"        try{delete tsp.rows;}catch(e){}"
			"        Object.defineProperty(tsp,'rows',{get:function(){"
			"          var r=[];"
			"          for(var c=this.firstChild;c;c=c.nextSibling)"
			"            if(c.nodeType===1&&c.tagName==='TR') r.push(c);"
			"          return r;"
			"        },configurable:true});"
			"      }"
			"      if (!tsp.insertRow) {"
			"        tsp.insertRow = function(idx) {"
			"          var tr = (this.ownerDocument||d).createElement('tr');"
			"          var rows = this.rows || [];"
			"          if (idx === undefined || idx === -1 || idx >= rows.length) {"
			"            this.appendChild(tr);"
			"          } else if (idx >= 0 && idx < rows.length) {"
			"            this.insertBefore(tr, rows[idx]);"
			"          }"
			"          return tr;"
			"        };"
			"      }"
			"    }"
			"  } catch(e) {}"
			/* Polyfill HTMLTableRowElement.rowIndex/sectionRowIndex/cells */
			"  try {"
			"    var trow = d.createElement('tr');"
			"    var trp = Object.getPrototypeOf(trow);"
			"    if (trp) {"
			"      var origRI = null;"
			"      try{origRI=Object.getOwnPropertyDescriptor(trp,'rowIndex');}catch(e){}"
			"      if (!origRI || origRI.configurable !== false) {"
			"        try{delete trp.rowIndex;}catch(e){}"
			"        Object.defineProperty(trp,'rowIndex',{get:function(){"
			"          var sec=this.parentNode;"
			"          if(!sec) return -1;"
			"          var tbl=sec.parentNode;"
			"          if(!tbl||tbl.tagName!=='TABLE') {"
			"            if(sec.tagName==='TABLE') tbl=sec;"
			"            else return -1;"
			"          }"
			"          var rows=[];"
			"          var th=tbl.tHead;"
			"          if(th) for(var c=th.firstChild;c;c=c.nextSibling)"
			"            if(c.nodeType===1&&c.tagName==='TR') rows.push(c);"
			"          var tbs=tbl.tBodies||[];"
			"          for(var bi=0;bi<tbs.length;bi++)"
			"            for(var c=tbs[bi].firstChild;c;c=c.nextSibling)"
			"              if(c.nodeType===1&&c.tagName==='TR') rows.push(c);"
			"          var tf=tbl.tFoot;"
			"          if(tf) for(var c=tf.firstChild;c;c=c.nextSibling)"
			"            if(c.nodeType===1&&c.tagName==='TR') rows.push(c);"
			"          for(var c=tbl.firstChild;c;c=c.nextSibling)"
			"            if(c.nodeType===1&&c.tagName==='TR') rows.push(c);"
			"          for(var ri=0;ri<rows.length;ri++)"
			"            if(rows[ri]===this) return ri;"
			"          return -1;"
			"        },configurable:true});"
			"      }"
			"      var origSRI = null;"
			"      try{origSRI=Object.getOwnPropertyDescriptor(trp,'sectionRowIndex');}catch(e){}"
			"      if (!origSRI || origSRI.configurable !== false) {"
			"        try{delete trp.sectionRowIndex;}catch(e){}"
			"        Object.defineProperty(trp,'sectionRowIndex',{get:function(){"
			"          var sec=this.parentNode;"
			"          if(!sec) return -1;"
			"          var idx=0;"
			"          for(var c=sec.firstChild;c;c=c.nextSibling){"
			"            if(c===this) return idx;"
			"            if(c.nodeType===1&&c.tagName==='TR') idx++;"
			"          }"
			"          return -1;"
			"        },configurable:true});"
			"      }"
			"      var origCells = null;"
			"      try{origCells=Object.getOwnPropertyDescriptor(trp,'cells');}catch(e){}"
			"      if (!origCells || origCells.configurable !== false) {"
			"        try{delete trp.cells;}catch(e){}"
			"        Object.defineProperty(trp,'cells',{get:function(){"
			"          var r=[];"
			"          for(var c=this.firstChild;c;c=c.nextSibling)"
			"            if(c.nodeType===1&&(c.tagName==='TD'||c.tagName==='TH')) r.push(c);"
			"          return r;"
			"        },configurable:true});"
			"      }"
			"    }"
			"  } catch(e) {}"
			/* Patch HTMLElement.click() to toggle checkbox/radio state */
			"  try {"
			"    var btn = d.createElement('div');"
			"    var bp = Object.getPrototypeOf(btn);"
			"    while(bp && !bp.hasOwnProperty('click')) bp = Object.getPrototypeOf(bp);"
			"    if (!bp) bp = Object.getPrototypeOf(d.createElement('div'));"
			"    if (bp) {"
			"      var origClick = bp.click;"
			"      bp.click = function() {"
			"        if (this.tagName === 'INPUT') {"
			"          var t = (this.type||'').toLowerCase();"
			"          if (t === 'checkbox') this.checked = !this.checked;"
			"          else if (t === 'radio') {"
			"            if(this.name && this.parentNode) {"
			"              var radios = this.parentNode.getElementsByTagName('input');"
			"              for(var ri=0;ri<radios.length;ri++)"
			"                if(radios[ri]!==this&&radios[ri].type==='radio'&&radios[ri].name===this.name)"
			"                  radios[ri].checked=false;"
			"            }"
			"            this.checked = true;"
			"          }"
			"          else if (t === 'submit') {"
			"            var form = this.parentNode;"
			"            while(form && form.tagName !== 'FORM') form = form.parentNode;"
			"            if (form && form.onsubmit) {"
			"              var se = d.createEvent('Event');"
			"              se.initEvent('submit',true,true);"
			"              se.preventDefault = function(){this.defaultPrevented=true;};"
			"              form.onsubmit(se);"
			"            }"
			"          }"
			"        }"
			"        if (origClick) origClick.call(this);"
			"      };"
			"    }"
			"  } catch(e) {}"
			/* A5: getSVGDocument on iframe/object/embed */
			"  try {"
			"    var svgDocFn = function(){return this.contentDocument;};"
			"    var ip2 = Object.getPrototypeOf(d.createElement('iframe'));"
			"    if(ip2) ip2.getSVGDocument = svgDocFn;"
			"    var op2 = Object.getPrototypeOf(d.createElement('object'));"
			"    if(op2 && op2 !== ip2) op2.getSVGDocument = svgDocFn;"
			"    var ep2 = Object.getPrototypeOf(d.createElement('embed'));"
			"    if(ep2 && ep2 !== ip2 && ep2 !== op2) ep2.getSVGDocument = svgDocFn;"
			"  } catch(e) {}"
			/* F4: object.data URI resolution — resolve relative URLs to absolute */
			"  try {"
			"    var obj = d.createElement('object');"
			"    var op = Object.getPrototypeOf(obj);"
			"    if (op) {"
			"      var origDataDesc = null;"
			"      var pp = op;"
			"      while(pp && !origDataDesc) {"
			"        origDataDesc = Object.getOwnPropertyDescriptor(pp, 'data');"
			"        if(!origDataDesc) pp = Object.getPrototypeOf(pp);"
			"      }"
			"      if (origDataDesc && origDataDesc.configurable !== false) {"
			"        var origDataGet = origDataDesc.get;"
			"        var origDataSet = origDataDesc.set;"
			"        Object.defineProperty(pp, 'data', {"
			"          get: function() {"
			"            var raw = origDataGet ? origDataGet.call(this) : this.getAttribute('data');"
			"            if (!raw) return raw;"
			"            if (/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(raw)) return raw;"
			"            var base = this.baseURI || d.baseURI || (d.location&&d.location.href) || '';"
			"            if (!base) return raw;"
			"            var i = base.lastIndexOf('/');"
			"            if (i >= 0) return base.substring(0, i + 1) + raw.replace(/^\\.\\//,'');"
			"            return raw;"
			"          },"
			"          set: origDataSet || function(v) { this.setAttribute('data', v); },"
			"          configurable: true"
			"        });"
			"      }"
			"    }"
			"  } catch(e) {}"
			/* A6: SVG element methods — walk up to highest element proto */
			"  try {"
			"    var ep = Object.getPrototypeOf(d.createElement('div'));"
			"    while(ep) {"
			"      var pp = Object.getPrototypeOf(ep);"
			"      if (!pp || pp === Object.prototype) break;"
			"      ep = pp;"
			"    }"
			"    if(ep && !ep.getNumberOfChars) {"
			"      ep.getNumberOfChars = function(){return (this.textContent||'').length;};"
			"    }"
			"    if(ep && !ep.getBBox) {"
			"      ep.getBBox = function(){"
			"        var w=parseFloat(this.getAttribute('width'))||0;"
			"        var h=parseFloat(this.getAttribute('height'))||0;"
			"        var x=parseFloat(this.getAttribute('x'))||0;"
			"        var y=parseFloat(this.getAttribute('y'))||0;"
			"        return {x:x,y:y,width:w,height:h};"
			"      };"
			"    }"
			"  } catch(e) {}"
			/* SVG animated length stub for width/height on SVG elements */
			"  try {"
			"    function svgAnimLen(el, attr) {"
			"      var v = parseFloat(el.getAttribute(attr)) || 0;"
			"      return {baseVal:{value:v,valueInSpecifiedUnits:v,unitType:1},"
			"              animVal:{value:v,valueInSpecifiedUnits:v,unitType:1}};"
			"    }"
			"    var svgns = 'http://www.w3.org/2000/svg';"
			"    var origCreateNS = p.createElementNS;"
			"    if (origCreateNS) {"
			"      p.createElementNS = function(ns, name) {"
			"        var el = origCreateNS.call(this, ns, name);"
			"        if (ns === svgns && el) {"
			"          var elp = Object.getPrototypeOf(el);"
			"          if (elp && !Object.getOwnPropertyDescriptor(elp, 'width')) {"
			"            ['width','height','x','y','cx','cy','r','rx','ry'].forEach(function(a){"
			"              Object.defineProperty(el, a, {"
			"                get: function(){return svgAnimLen(this,a);},"
			"                configurable:true"
			"              });"
			"            });"
			"          }"
			"          if (!el.ownerSVGElement) {"
			"            Object.defineProperty(el, 'ownerSVGElement', {"
			"              get: function(){"
			"                var n=this.parentNode;"
			"                while(n && !(n.tagName==='svg'||n.tagName==='SVG')) n=n.parentNode;"
			"                return n;"
			"              },configurable:true"
			"            });"
			"          }"
			"        }"
			"        return el;"
			"      };"
			"    }"
			"  } catch(e) {}"
			/* Radio button mutual exclusion via checked setter */
			"  try {"
			"    var inp = d.createElement('input');"
			"    var inpP = Object.getPrototypeOf(inp);"
			"    if (inpP) {"
			"      var checkedDesc = null;"
			"      var p2 = inpP;"
			"      while(p2 && !checkedDesc) {"
			"        checkedDesc = Object.getOwnPropertyDescriptor(p2, 'checked');"
			"        if(!checkedDesc) p2 = Object.getPrototypeOf(p2);"
			"      }"
			"      if (checkedDesc && checkedDesc.set) {"
			"        var origSet = checkedDesc.set;"
			"        var origGet = checkedDesc.get;"
			"        Object.defineProperty(p2, 'checked', {"
			"          get: function() { if(this.__checkedDirty)return this.__checkedVal; return origGet?origGet.call(this):false; },"
			"          set: function(v) {"
			"            this.__checkedDirty=true;this.__checkedVal=!!v;origSet.call(this, v);"
			"            if (v && this.type === 'radio' && this.name) {"
			"              var form = this.parentNode;"
			"              while(form && form.tagName !== 'FORM') form = form.parentNode;"
			"              var container = form || this.parentNode;"
			"              if (container) {"
			"                var radios = container.getElementsByTagName('input');"
			"                for(var ri=0;ri<radios.length;ri++)"
			"                  if(radios[ri]!==this&&radios[ri].type==='radio'&&radios[ri].name===this.name)"
			"                    radios[ri].checked=false;"
			"              }"
			"            }"
			"          },"
			"          configurable: true"
			"        });"
			"      }"
			"    }"
			"  } catch(e) {}"
			/* B1: form.elements polyfill */
			"  try {"
			"    var frm = d.createElement('form');"
			"    var fp = Object.getPrototypeOf(frm);"
			"    if (fp) {"
			"      try{delete fp.elements;}catch(e){}"
			"      Object.defineProperty(fp, 'elements', {"
			"        get: function() {"
			"          var els = [];"
			"          var tags = {INPUT:1,SELECT:1,TEXTAREA:1,BUTTON:1};"
			"          function walk(n) {"
			"            for(var c=n.firstChild;c;c=c.nextSibling) {"
			"              if(c.nodeType===1) {"
			"                if(tags[c.tagName]) els.push(c);"
			"                if(c.tagName!=='FORM') walk(c);"
			"              }"
			"            }"
			"          }"
			"          walk(this);"
			"          var proxy = {length: els.length};"
			"          for(var i=0;i<els.length;i++) {"
			"            proxy[i] = els[i];"
			"            if(els[i].name) proxy[els[i].name] = els[i];"
			"          }"
			"          return proxy;"
			"        },"
			"        configurable: true"
			"      });"
			"      try{delete fp.length;}catch(e){}"
			"      Object.defineProperty(fp, 'length', {"
			"        get: function() { return this.elements.length; },"
			"        configurable: true"
			"      });"
			"    }"
			"  } catch(e) {}"
			/* Wrap removeChild to notify Range pre-removing steps */
			"  try {"
			"    var nd = d.createElement('div');"
			"    var np = Object.getPrototypeOf(nd);"
			"    while(np && !np.hasOwnProperty('removeChild')) np = Object.getPrototypeOf(np);"
			"    if (np && np.removeChild && typeof Range === 'function' && Range._preRemove) {"
			"      var _orc = np.removeChild;"
			"      np.removeChild = function(c) {"
			"        Range._preRemove(c, this);"
			"        return _orc.call(this, c);"
			"      };"
			"    }"
			"  } catch(e) {}"
			"  return 'ok';"
			"})()";
		JSValue r = JS_Eval(ctx, patch_src, sizeof(patch_src) - 1,
				    "<dom-patch>", JS_EVAL_TYPE_GLOBAL);
		if (JS_IsException(r)) {
			JSValue exc = JS_GetException(ctx);
			JSValue msg = JS_GetPropertyStr(ctx, exc, "message");
			const char *s = JS_ToCString(ctx, msg);
			ALOG_QJS("dom-patch EXCEPTION: %s", s ? s : "(null)");
			if (s) JS_FreeCString(ctx, s);
			JS_FreeValue(ctx, msg);
			JS_FreeValue(ctx, exc);
		} else if (JS_IsString(r)) {
			const char *s = JS_ToCString(ctx, r);
			ALOG_QJS("dom-patch result: %s", s ? s : "(null)");
			if (s) JS_FreeCString(ctx, s);
		}
		JS_FreeValue(ctx, r);
	}

	/* ── getComputedStyle polyfill ────────────────────────────
	 * Minimal implementation for acid3 CSS selector tests.
	 * Parses <style> elements, matches basic selectors, returns
	 * a CSSStyleDeclaration-like object with property values. */
	{
		static const char gcs_src[] =
			"(function(){"
			"  /* Override native getComputedStyle stub (returns undefined) */"
			/* Simple CSS selector matcher — handles:
			 * tag, .class, #id, [attr], [attr=val], [attr|=val],
			 * *, :first-child, :root, :empty, combinations */
			/* Decode CSS escape sequences: \\NNNNNN → char */
			"  function decodeCssEsc(s) {"
			"    return s.replace(/\\\\([0-9a-fA-F]{1,6})\\s?/g, function(m,h){"
			"      return String.fromCharCode(parseInt(h,16));"
			"    });"
			"  }"
			/* Match a single simple selector (no combinators) */
			"  function matchSimple(el, s) {"
			"    if (!el || el.nodeType !== 1) return false;"
			"    if (s === '*') return true;"
			"    if (s[0] === '#') return el.getAttribute('id') === s.substring(1);"
			"    if (s[0] === '.') {"
			"      var classes = (el.getAttribute('class')||'').split(/[\\t\\n\\r\\f ]+/);"
			"      var cls = decodeCssEsc(s.substring(1));"
			""
			"      for(var ci=0;ci<classes.length;ci++) if(classes[ci]===cls) return true;"
			"      return false;"
			"    }"
			"    if (s[0] === '[') {"
			"      var am = s.match(/^\\[([\\w-]+)(?:([~|^$*]?)=(['\"]?)([^'\"\\]]*?)\\3)?\\]$/);"
			"      if (!am) return false;"
			"      var av = el.getAttribute(am[1]);"
			"      if (av === null) return false;"
			"      if (!am[2] && !am[4]) return true;"
			"      if (!am[2] || am[2]==='') return av === am[4];"
			"      if (am[2]==='|') return av===am[4]||av.indexOf(am[4]+'-')===0;"
			"      if (am[2]==='~') return (' '+av+' ').indexOf(' '+am[4]+' ')>=0;"
			"      if (am[2]==='^') return av.indexOf(am[4])===0;"
			"      if (am[2]==='$') return av.indexOf(am[4],av.length-am[4].length)!==-1;"
			"      if (am[2]==='*') return av.indexOf(am[4])>=0;"
			"      return false;"
			"    }"
			"    if (s===':root') return el===(el.ownerDocument||el).documentElement;"
			"    if (s===':empty') {"
			"      var ch=el.firstChild;"
			"      while(ch){"
			"        if(ch.nodeType===1) return false;"
			"        if(ch.nodeType===3&&ch.data.length>0) return false;"
			"        ch=ch.nextSibling;"
			"      }"
			"      return true;"
			"    }"
			"    if (s===':first-child') return el.parentNode&&el.parentNode.nodeType===1&&!el.previousElementSibling;"
			"    if (s===':last-child') return el.parentNode&&el.parentNode.nodeType===1&&!el.nextElementSibling;"
			"    if (s===':only-child') return el.parentNode&&el.parentNode.nodeType===1&&!el.previousElementSibling&&!el.nextElementSibling;"
			"    if (s===':enabled') {"
			"      var tn=el.tagName&&el.tagName.toLowerCase();"
			"      if(tn==='input'||tn==='select'||tn==='textarea'||tn==='button')"
			"        return !el.disabled;"
			"      return false;"
			"    }"
			"    if (s===':disabled') {"
			"      var tn=el.tagName&&el.tagName.toLowerCase();"
			"      if(tn==='input'||tn==='select'||tn==='textarea'||tn==='button')"
			"        return !!el.disabled;"
			"      return false;"
			"    }"
			"    if (s===':checked') { var tn2=(el.tagName||'').toLowerCase();if(tn2==='input'){var tp=(el.type||'').toLowerCase();if(tp!=='checkbox'&&tp!=='radio')return false;}else if(tn2!=='option')return false;return !!el.checked; }"
			"    if (s===':first-of-type'||s===':last-of-type'||s===':only-of-type') {"
			"      var tn=el.tagName,p=el.parentNode;"
			"      if (!p) return false;"
			"      var first=true,last=true,sib;"
			"      for(sib=el.previousElementSibling;sib;sib=sib.previousElementSibling)"
			"        if(sib.tagName===tn){first=false;break;}"
			"      for(sib=el.nextElementSibling;sib;sib=sib.nextElementSibling)"
			"        if(sib.tagName===tn){last=false;break;}"
			"      if (s===':first-of-type') return first;"
			"      if (s===':last-of-type') return last;"
			"      return first&&last;"
			"    }"
			"    if (s.indexOf(':lang(')===0) {"
			"      var lang=s.substring(6,s.length-1);"
			"      var n=el;while(n){var l=n.getAttribute&&n.getAttribute('lang');"
			"        if(l) return l===lang||l.indexOf(lang+'-')===0;"
			"        n=n.parentNode;}"
			"      return false;"
			"    }"
			"    if (s.indexOf(':nth-of-type(')===0) {"
			"      var expr=s.substring(13,s.length-1);"
			"      var tn=el.tagName,idx=0;"
			"      for(var sib=el.previousElementSibling;sib;sib=sib.previousElementSibling)"
			"        if(sib.tagName===tn) idx++;"
			"      idx++;"
			"      if(expr==='odd') return idx%2===1;"
			"      if(expr==='even') return idx%2===0;"
			"      if(/^\\d+$/.test(expr)) return idx===parseInt(expr);"
			"      var ab = expr.match(/^(-?\\d*)n\\s*([+-]\\s*\\d+)?$/);"
			"      if (ab) {"
			"        var a = ab[1]===''||ab[1]==='+' ? 1 : ab[1]==='-' ? -1 : parseInt(ab[1]);"
			"        var b = ab[2] ? parseInt(ab[2].replace(/\\s/g,'')) : 0;"
			"        if (a === 0) return idx === b;"
			"        return (idx - b) % a === 0 && (idx - b) / a >= 0;"
			"      }"
			"      return false;"
			"    }"
			"    if (s.indexOf(':nth-child(')===0) {"
			"      var expr = s.substring(11, s.length-1);"
			"      var idx = 0; var sib = el.previousElementSibling;"
			"      while (sib) { idx++; sib = sib.previousElementSibling; }"
			"      idx++;" /* 1-based */
			"      if (expr === 'odd') return idx % 2 === 1;"
			"      if (expr === 'even') return idx % 2 === 0;"
			"      if (/^\\d+$/.test(expr)) return idx === parseInt(expr);"
			/* an+b form */
			"      var ab = expr.match(/^(-?\\d*)n\\s*([+-]\\s*\\d+)?$/);"
			"      if (ab) {"
			"        var a = ab[1]===''||ab[1]==='+' ? 1 : ab[1]==='-' ? -1 : parseInt(ab[1]);"
			"        var b = ab[2] ? parseInt(ab[2].replace(/\\s/g,'')) : 0;"
			"        if (a === 0) return idx === b;"
			"        return (idx - b) % a === 0 && (idx - b) / a >= 0;"
			"      }"
			"      return false;"
			"    }"
			"    if (s.indexOf(':nth-last-child(')===0) {"
			"      var expr = s.substring(16, s.length-1);"
			"      var idx = 0; var sib = el.nextElementSibling;"
			"      while (sib) { idx++; sib = sib.nextElementSibling; }"
			"      idx++;"
			"      if (expr === 'odd') return idx % 2 === 1;"
			"      if (expr === 'even') return idx % 2 === 0;"
			"      if (/^\\d+$/.test(expr)) return idx === parseInt(expr);"
			"      var ab = expr.match(/^(-?\\d*)n\\s*([+-]\\s*\\d+)?$/);"
			"      if (ab) {"
			"        var a = ab[1]===''||ab[1]==='+' ? 1 : ab[1]==='-' ? -1 : parseInt(ab[1]);"
			"        var b = ab[2] ? parseInt(ab[2].replace(/\\s/g,'')) : 0;"
			"        if (a === 0) return idx === b;"
			"        return (idx - b) % a === 0 && (idx - b) / a >= 0;"
			"      }"
			"      return false;"
			"    }"
			"    if (s.indexOf(':nth-last-of-type(')===0) {"
			"      var expr = s.substring(18, s.length-1);"
			"      var tn=el.tagName,idx=0;"
			"      for(var sib=el.nextElementSibling;sib;sib=sib.nextElementSibling)"
			"        if(sib.tagName===tn) idx++;"
			"      idx++;"
			"      if(expr==='odd') return idx%2===1;"
			"      if(expr==='even') return idx%2===0;"
			"      if(/^\\d+$/.test(expr)) return idx===parseInt(expr);"
			"      var ab = expr.match(/^(-?\\d*)n\\s*([+-]\\s*\\d+)?$/);"
			"      if (ab) {"
			"        var a = ab[1]===''||ab[1]==='+' ? 1 : ab[1]==='-' ? -1 : parseInt(ab[1]);"
			"        var b = ab[2] ? parseInt(ab[2].replace(/\\s/g,'')) : 0;"
			"        if (a === 0) return idx === b;"
			"        return (idx - b) % a === 0 && (idx - b) / a >= 0;"
			"      }"
			"      return false;"
			"    }"
			"    if (s.indexOf(':not(')===0 && s[s.length-1]===')') {"
			"      return !matchCompound(el, s.substring(5, s.length-1));"
			"    }"
			"    if (s.match(/^[a-zA-Z][\\w-]*$/)) {"
			"      return el.tagName&&el.tagName.toLowerCase()===s.toLowerCase();"
			"    }"
			"    return false;"
			"  }"
			/* Match compound selector: tag.class#id[attr]:pseudo (no spaces) */
			"  function matchCompound(el, sel) {"
			"    if (!el || el.nodeType !== 1) return false;"
			"    sel = sel.trim();"
			"    if (sel === '*') return true;"
			/* Tokenize compound selector into parts */
			"    var parts = [];"
			"    var re = /(:(?:not|lang|nth-child|nth-last-child|nth-of-type|nth-last-of-type)\\([^)]+\\)|[.#:](?:\\\\[0-9a-fA-F]{1,6}\\s?|\\w[\\w-]*)+|\\[[^\\]]+\\]|[a-zA-Z][\\w-]*|\\*)/g;"
			"    var m;"
			"    while ((m = re.exec(sel)) !== null) parts.push(m[1]);"
			"    if (parts.length === 0) return false;"
			"    for (var i = 0; i < parts.length; i++) {"
			"      if (!matchSimple(el, parts[i])) return false;"
			"    }"
			"    return true;"
			"  }"
			/* Full selector with combinators: space > + ~ */
			"  function tokenizeSel(sel) {"
			"    var tokens = [], cur = '', depth = 0;"
			"    for (var i = 0; i < sel.length; i++) {"
			"      var c = sel[i];"
			"      if (c === '(') { depth++; cur += c; continue; }"
			"      if (c === ')') { depth--; cur += c; continue; }"
			"      if (depth > 0) { cur += c; continue; }"
			"      if (c === '>' || c === '+' || c === '~') {"
			"        if (cur.trim()) tokens.push(cur.trim());"
			"        tokens.push(c); cur = '';"
			"      } else if (c === ' ' || c === '\\t') {"
			"        if (cur.trim()) {"
			"          var j = i + 1;"
			"          while (j < sel.length && (sel[j] === ' ' || sel[j] === '\\t')) j++;"
			"          if (j < sel.length && '>+~'.indexOf(sel[j]) >= 0) { i = j - 1; continue; }"
			"          tokens.push(cur.trim()); tokens.push(' '); cur = '';"
			"        }"
			"      } else { cur += c; }"
			"    }"
			"    if (cur.trim()) tokens.push(cur.trim());"
			"    return tokens;"
			"  }"
			"  function matchTokens(el, tokens, i) {"
			"    if (!el || el.nodeType !== 1) return false;"
			"    if (!matchCompound(el, tokens[i])) return false;"
			"    if (i === 0) return true;"
			"    var comb = tokens[i-1];"
			"    if (comb === '>') return matchTokens(el.parentNode, tokens, i-2);"
			"    if (comb === '+') return matchTokens(el.previousElementSibling, tokens, i-2);"
			"    if (comb === '~') {"
			"      for (var sib=el.previousElementSibling;sib;sib=sib.previousElementSibling)"
			"        if (matchTokens(sib, tokens, i-2)) return true;"
			"      return false;"
			"    }"
			"    if (comb === ' ') {"
			"      for (var anc=el.parentNode;anc&&anc.nodeType===1;anc=anc.parentNode)"
			"        if (matchTokens(anc, tokens, i-2)) return true;"
			"      return false;"
			"    }"
			"    return false;"
			"  }"
			"  function matchesSelector(el, sel) {"
			"    if (!el || el.nodeType !== 1) return false;"
			"    var tokens = tokenizeSel(sel.trim());"
			"    if (tokens.length === 0) return false;"
			"    return matchTokens(el, tokens, tokens.length - 1);"
			"  }"
			/* Evaluate @media query — simplified for Acid3 */
			"  function parseDimPx(s) {"
			"    if (!s) return 0;"
			"    var n = parseFloat(s);"
			"    if (isNaN(n)) return 0;"
			"    if (s.indexOf('em') >= 0) return n * 16;"
			"    return n;"
			"  }"
			"  function getViewport(doc) {"
			"    var fe = doc && doc.__frameElement;"
			"    if (fe) {"
			"      var st = fe.getAttribute && fe.getAttribute('style');"
			"      var w = 0, h = 0;"
			"      if (st) {"
			"        var hm = st.match(/height\\s*:\\s*(\\d+)/);"
			"        var wm = st.match(/width\\s*:\\s*(\\d+)/);"
			"        if (hm) h = parseInt(hm[1]);"
			"        if (wm) w = parseInt(wm[1]);"
			"      }"
			"      return {w:w, h:h};"
			"    }"
			"    var de = doc && doc.documentElement;"
			"    return {"
			"      w: de ? de.clientWidth || 0 : 0,"
			"      h: de ? de.clientHeight || 0 : 0"
			"    };"
			"  }"
			"  function evalMedia(q, doc) {"
			"    q = q.trim();"
			"    if (!q || q === 'all') return true;"
			"    var parts = q.split(',');"
			"    for (var i = 0; i < parts.length; i++) {"
			"      var p = parts[i].trim();"
			"      if (p === 'all') return true;"
			"      var neg = false;"
			"      if (p.indexOf('not ') === 0) { neg = true; p = p.substring(4).trim(); }"
			"      else if (p.indexOf('only ') === 0) { p = p.substring(5).trim(); }"
			"      var ok = true;"
			"      var conds = p.split(/\\s+and\\s+/);"
			"      for (var j = 0; j < conds.length; j++) {"
			"        var c = conds[j].trim();"
			"        if (c === 'all') continue;"
			"        var fm = c.match(/^\\(([^)]+)\\)$/);"
			"        if (!fm) { ok = false; break; }"
			"        var feat = fm[1].trim();"
			"        var fv = feat.match(/:\\s*(.+)/);"
			"        var fval = fv ? parseDimPx(fv[1]) : 0;"
			/* Color display: color depth ~8, monochrome depth 0 */
			"        if (feat.indexOf('min-color') === 0) { if (fval > 8) { ok=false; break; } continue; }"
			"        if (feat.indexOf('max-color') === 0) { if (fval < 8) { ok=false; break; } continue; }"
			"        if (feat.indexOf('min-monochrome') === 0) { if (fval > 0) { ok=false; break; } continue; }"
			"        if (feat.indexOf('max-monochrome') === 0) { continue; }"
			"        if (feat.indexOf('min-height') >= 0) {"
			"          var vp = getViewport(doc);"
			"          if (vp.h < fval) { ok = false; break; } continue;"
			"        }"
			"        if (feat.indexOf('min-width') >= 0) {"
			"          var vp = getViewport(doc);"
			"          if (vp.w < fval) { ok = false; break; } continue;"
			"        }"
			"        if (feat.indexOf('max-height') >= 0) {"
			"          var vp = getViewport(doc);"
			"          if (vp.h > fval) { ok = false; break; } continue;"
			"        }"
			"        if (feat.indexOf('max-width') >= 0) {"
			"          var vp = getViewport(doc);"
			"          if (vp.w > fval) { ok = false; break; } continue;"
			"        }"
			"        ok = false; break;"
			"      }"
			"      if (neg) ok = !ok;"
			"      if (ok) return true;"
			"    }"
			"    return false;"
			"  }"
			/* Parse CSS rules from text, handling @media blocks */
			"  function parseRules(text, doc) {"
			"    text = text.replace(/\\/\\*[\\s\\S]*?\\*\\//g, '');"
			"    var rules = [];"
			"    var cssValid = {"
			"      'white-space':{normal:1,nowrap:1,pre:1,'pre-wrap':1,'pre-line':1,'break-spaces':1},"
			"      'text-transform':{none:1,capitalize:1,uppercase:1,lowercase:1,'full-width':1},"
			"      'float':{left:1,right:1,none:1,'inline-start':1,'inline-end':1}"
			"    };"
			"    function addRule(sel, body) {"
			"      var props = {};"
			"      body.split(';').forEach(function(p){"
			"        var kv = p.split(':');"
			"        if (kv.length >= 2) {"
			"          var k = kv[0].trim();"
			"          var v = kv.slice(1).join(':').trim();"
			"          if (v.indexOf('!') >= 0) v = v.replace(/\\s*!\\s*important\\s*$/, '');"
			"          if (cssValid[k] && !cssValid[k][v]) return;"
			"          props[k] = v;"
			"        }"
			"      });"
			"      var sels = sel.split(',');"
			"      for (var i = 0; i < sels.length; i++)"
			"        rules.push({ selector: sels[i].trim(), props: props });"
			"    }"
			"    var i = 0;"
			"    while (i < text.length) {"
			"      var brace = text.indexOf('{', i);"
			"      if (brace < 0) break;"
			"      var sel = text.substring(i, brace).trim();"
			"      if (sel.indexOf('@media') === 0) {"
			"        var depth = 1, j = brace + 1;"
			"        while (j < text.length && depth > 0) {"
			"          if (text[j] === '{') depth++;"
			"          if (text[j] === '}') depth--;"
			"          j++;"
			"        }"
			"        var inner = text.substring(brace + 1, j - 1);"
			"        var mq = sel.substring(6).trim();"
			"        if (evalMedia(mq, doc)) {"
			"          var innerRules = parseRules(inner, doc);"
			"          rules = rules.concat(innerRules);"
			"        }"
			"        i = j;"
			"      } else {"
			"        var close = text.indexOf('}', brace);"
			"        if (close < 0) break;"
			"        var body = text.substring(brace + 1, close);"
			"        if (sel) addRule(sel, body);"
			"        i = close + 1;"
			"      }"
			"    }"
			"    return rules;"
			"  }"
			/* Convert CSS property name to camelCase */
			"  function camelCase(name) {"
			"    return name.replace(/-([a-z])/g, function(m,c){return c.toUpperCase();});"
			"  }"
			/* CSS specificity: returns numeric weight */
			"  function calcSpec(sel) {"
			"    var tokens = tokenizeSel(sel);"
			"    var a=0,b=0,c=0;"
			"    var cre = /(:(?:not|lang|nth-child|nth-last-child|nth-of-type|nth-last-of-type)\\([^)]+\\)|[.#:](?:\\\\[0-9a-fA-F]{1,6}\\s?|\\w[\\w-]*)+|\\[[^\\]]+\\]|[a-zA-Z][\\w-]*|\\*)/g;"
			"    for (var i=0;i<tokens.length;i+=2){"
			"      var m2,sub=tokens[i];"
			"      cre.lastIndex=0;"
			"      while((m2=cre.exec(sub))!==null){"
			"        var p=m2[1];"
			"        if(p==='*') continue;"
			"        if(p[0]==='#') a++;"
			"        else if(p[0]==='.'||p[0]==='['||(p[0]===':'&&p.indexOf(':not(')!==0)) b++;"
			"        else if(p.match(/^[a-zA-Z]/)) c++;"
			"        if(p.indexOf(':not(')===0){"
			"          var inner=p.substring(5,p.length-1);"
			"          var is=calcSpec(inner);"
			"          a+=Math.floor(is/10000);b+=Math.floor((is%10000)/100);c+=is%100;"
			"        }"
			"      }"
			"    }"
			"    return a*10000+b*100+c;"
			"  }"
			/* getComputedStyle implementation */
			"  globalThis.getComputedStyle = function(el, pseudo) {"
			""
			"    var result = {};"
			"    var doc = el.ownerDocument || document;"
			"    var styles = doc.getElementsByTagName('style');"
			"    var allRules = [];"
			"    for (var i = 0; i < styles.length; i++) {"
			"      var text = styles[i].textContent || '';"
			"      allRules = allRules.concat(parseRules(text, doc));"
			"    }"
			/* Collect matching rules with specificity, sort, then apply */
			"    var matches = [];"
			"    for (var i = 0; i < allRules.length; i++) {"
			""
			"      if (matchesSelector(el, allRules[i].selector)) {"
			"        matches.push({props:allRules[i].props,spec:calcSpec(allRules[i].selector),order:i});"
			"      }"
			"    }"
			"    matches.sort(function(x,y){ return x.spec-y.spec || x.order-y.order; });"
			""
			"    for (var i = 0; i < matches.length; i++) {"
			"      for (var k in matches[i].props) {"
			"        result[camelCase(k)] = matches[i].props[k];"
			"        result[k] = matches[i].props[k];"
			"      }"
			"    }"
			/* Validate CSS values — discard invalid values, use initial */
			"    var validCursors = {auto:1,'default':1,none:1,'context-menu':1,help:1,pointer:1,progress:1,wait:1,cell:1,crosshair:1,text:1,'vertical-text':1,alias:1,copy:1,move:1,'no-drop':1,'not-allowed':1,'e-resize':1,'n-resize':1,'ne-resize':1,'nw-resize':1,'s-resize':1,'se-resize':1,'sw-resize':1,'w-resize':1,'ew-resize':1,'ns-resize':1,'nesw-resize':1,'nwse-resize':1,'col-resize':1,'row-resize':1,'all-scroll':1,grab:1,grabbing:1,'zoom-in':1,'zoom-out':1};"
			"    if (result.cursor && !validCursors[result.cursor]) result.cursor = 'auto';"
			/* CSS initial values for commonly tested properties */
			"    if (!result.textTransform) result.textTransform = 'none';"
			"    if (!result.whiteSpace) result.whiteSpace = 'normal';"
			"    if (!result.cursor) result.cursor = 'auto';"
			/* Also check inline style attribute */
			"    var inl = el.getAttribute('style');"
			"    if (inl) {"
			"      inl.split(';').forEach(function(p){"
			"        var kv = p.split(':');"
			"        if (kv.length >= 2) {"
			"          var k = kv[0].trim(), v = kv.slice(1).join(':').trim();"
			"          result[camelCase(k)] = v;"
			"          result[k] = v;"
			"        }"
			"      });"
			"    }"
			"    return result;"
			"  };"
			"})()";
		JSValue gcs = JS_Eval(ctx, gcs_src, sizeof(gcs_src) - 1,
				      "<gcs-patch>", JS_EVAL_TYPE_GLOBAL);
		if (JS_IsException(gcs)) {
			JSValue exc = JS_GetException(ctx);
			JSValue msg = JS_GetPropertyStr(ctx, exc, "message");
			const char *s = JS_ToCString(ctx, msg);
			ALOG_QJS("gcs-patch EXCEPTION: %s", s ? s : "(null)");
			if (s) JS_FreeCString(ctx, s);
			JS_FreeValue(ctx, msg);
			JS_FreeValue(ctx, exc);
		} else {
			ALOG_QJS("gcs-patch: OK (len=%zu)", sizeof(gcs_src) - 1);
		}
		JS_FreeValue(ctx, gcs);
	}

	/* ── element.style polyfill ──────────────────────────────
	 * Override the native stub to parse inline style attribute
	 * and expose CSS properties including cssFloat alias. */
	{
		static const char style_src[] =
			"(function(){"
			"  function parseStyle(el) {"
			"    var result = {};"
			"    var inl = el.getAttribute && el.getAttribute('style');"
			"    if (inl) {"
			"      inl.split(';').forEach(function(p){"
			"        var kv = p.split(':');"
			"        if (kv.length >= 2) {"
			"          var k = kv[0].trim(), v = kv.slice(1).join(':').trim();"
			"          var cc = k.replace(/-([a-z])/g, function(m,c){return c.toUpperCase();});"
			"          result[cc] = v;"
			"          result[k] = v;"
			"          if (k === 'float') result.cssFloat = v;"
			"        }"
			"      });"
			"    }"
			"    return result;"
			"  }"
			"  try {"
			"    var el = document.createElement('div');"
			"    var protos = [];"
			"    var p = Object.getPrototypeOf(el);"
			"    while (p) { protos.push(p); p = Object.getPrototypeOf(p); }"
			"    var found = false;"
			"    for (var i = 0; i < protos.length; i++) {"
			"      try {"
			"        var d = Object.getOwnPropertyDescriptor(protos[i], 'style');"
			"        if (d) {"
			"          if (d.configurable) {"
			"            Object.defineProperty(protos[i], 'style', {"
			"              get: function() { return parseStyle(this); },"
			"              configurable: true"
			"            });"
			"          } else {"
			"            delete protos[i].style;"
			"            Object.defineProperty(protos[i], 'style', {"
			"              get: function() { return parseStyle(this); },"
			"              configurable: true"
			"            });"
			"          }"
			"          found = true; break;"
			"        }"
			"      } catch(e2) {}"
			"    }"
			"  } catch(e) {}"
			"})()";
		ALOG_QJS("style-patch: evaluating (len=%zu)", sizeof(style_src) - 1);
		JSValue sv = JS_Eval(ctx, style_src, sizeof(style_src) - 1,
				     "<style-patch>", JS_EVAL_TYPE_GLOBAL);
		if (JS_IsException(sv)) {
			JSValue exc = JS_GetException(ctx);
			JSValue msg = JS_GetPropertyStr(ctx, exc, "message");
			const char *s = JS_ToCString(ctx, msg);
			ALOG_QJS("style-patch EXCEPTION: %s", s ? s : "(null)");
			if (s) JS_FreeCString(ctx, s);
			JS_FreeValue(ctx, msg);
			JS_FreeValue(ctx, exc);
		} else {
			ALOG_QJS("style-patch: OK");
		}
		JS_FreeValue(ctx, sv);
	}

	NSLOG(quickjs, DEBUG,
	      "QuickJS: thread created (ctx=%p win=%p doc=%p)",
	      (void *)ctx, win_priv, doc_priv);
	ALOG_QJS("thread created (ctx=%p win=%p doc=%p)",
		 (void *)ctx, win_priv, doc_priv);

	*thread = t;
	return NSERROR_OK;
}

nserror js_closethread(jsthread *thread)
{
	if (thread == NULL)
		return NSERROR_OK;

	NSLOG(quickjs, DEBUG, "QuickJS: closing thread (ctx=%p)",
	      (void *)thread->ctx);

#ifndef QJSCORE_TEST_BUILD
	qjsw_closedown_thread(thread->ctx);
#endif

	return NSERROR_OK;
}

static void qjs_destroythread(jsthread *t)
{
	assert(t->pending_destroy);
	assert(t->in_use == 0);

	jsheap *heap = t->heap;
	NSLOG(quickjs, DEBUG, "QuickJS: thread destroyed (ctx=%p)",
	      (void *)t->ctx);

	JS_FreeContext(t->ctx);
	free(t);

	JS_RunGC(heap->rt);
	heap->live_threads--;

	if (heap->pending_destroy && heap->live_threads == 0)
		qjs_destroyheap(heap);
}

void js_destroythread(jsthread *thread)
{
	if (thread == NULL)
		return;
	thread->pending_destroy = true;
	if (thread->in_use == 0)
		qjs_destroythread(thread);
}

/* ══════════════════════════════════════════════════════════════════════════
 * Script execution — documented in js.h
 * ══════════════════════════════════════════════════════════════════════════ */

bool js_exec(jsthread *thread, const uint8_t *txt, size_t txtlen,
	     const char *name)
{
	if (thread == NULL || txt == NULL || txtlen == 0)
		return false;
	if (thread->pending_destroy) {
		NSLOG(quickjs, DEEPDEBUG,
		      "QuickJS: skipping exec — thread pending destroy");
		return false;
	}

	qjs_enter_thread(thread);
	qjs_reset_exec_timer(thread->heap);
	thread->heap->exec_count++;

	/* Log every exec for crash diagnosis — direct logcat, bypasses NSLOG */
	{
		JSMemoryUsage mem;
		JS_ComputeMemoryUsage(thread->heap->rt, &mem);
		ALOG_QJS("exec #%u: name=%s len=%zu jsmem=%ldKB",
			 thread->heap->exec_count,
			 name ? name : "?",
			 txtlen,
			 (long)(mem.memory_used_size / 1024));
	}

	/* Copy script into a stable buffer — NetSurf's fetch buffer may
	 * be freed/reused during parsing on constrained 32-bit targets. */
	char *buf = malloc(txtlen + 1);
	if (!buf) {
		qjs_leave_thread(thread);
		return false;
	}
	memcpy(buf, txt, txtlen);
	buf[txtlen] = '\0';

	JSValue result = JS_Eval(thread->ctx,
				 buf, txtlen,
				 name ? name : "?",
				 JS_EVAL_TYPE_GLOBAL);
	free(buf);

	thread->heap->exec_timing = false;

	ALOG_QJS("exec #%u done: name=%s exc=%d",
		 thread->heap->exec_count, name ? name : "?",
		 JS_IsException(result));

	bool ret = false;
	if (JS_IsException(result)) {
		NSLOG(jserrors, DEBUG, "QuickJS: exception in js_exec(%s)",
		      name ? name : "?");
		qjs_log_exception(thread->ctx);
	} else if (JS_IsBool(result)) {
		/* Boolean result propagates directly */
		ret = (JS_ToBool(thread->ctx, result) != 0);
	} else {
		/* Non-exception, non-bool: ran successfully → return true */
		ret = true;
	}

	JS_FreeValue(thread->ctx, result);
	qjs_leave_thread(thread);
	return ret;
}

/* ══════════════════════════════════════════════════════════════════════════
 * Event / DOM API — Phase 5 implementations via qjsw_helpers
 * ══════════════════════════════════════════════════════════════════════════ */

#ifndef QJSCORE_TEST_BUILD
/* Full implementations — require libdom and corestrings */

bool js_fire_event(jsthread *thread, const char *type,
		   struct dom_document *doc, struct dom_node *target)
{
	dom_exception exc;
	dom_event *evt;
	dom_event_target *body;

	NSLOG(quickjs, DEBUG, "js_fire_event: %s (doc=%p, target=%p)", type, doc,
	      target);
	ALOG_QJS("fire_event: %s (doc=%p, target=%p)", type, (void *)doc,
		 (void *)target);

	if (strcmp(type, "load") != 0)
		return true;

	/* Element-targeted load events (e.g. iframe onload) */
	if (target != NULL) {
		JSContext *ctx = thread->ctx;
		JSValue node = qjsw_push_node(ctx, target);
		if (!JS_IsUndefined(node)) {
			/* Fire inline onload handler */
			JSValue handler = JS_GetPropertyStr(ctx, node, "onload");
			if (JS_IsFunction(ctx, handler)) {
				JSValue event_obj = JS_NewObject(ctx);
				JS_SetPropertyStr(ctx, event_obj, "type",
					JS_NewString(ctx, "load"));
				JS_SetPropertyStr(ctx, event_obj, "target",
					JS_DupValue(ctx, node));
				JSValue result = qjsw_pcall(ctx, handler,
					node, 1, &event_obj, true);
				JS_FreeValue(ctx, result);
				JS_FreeValue(ctx, event_obj);
			}
			JS_FreeValue(ctx, handler);
		}
		JS_FreeValue(ctx, node);
		return true;
	}

	exc = dom_event_create(&evt);
	if (exc != DOM_NO_ERR) return true;
	exc = dom_event_init(evt, corestring_dom_load, false, false);
	if (exc != DOM_NO_ERR) {
		dom_event_unref(evt);
		return true;
	}

	qjs_enter_thread(thread);
	JSContext *ctx = thread->ctx;

	/* Look for "load" handler on Window (global object) */
	JSValue global = JS_GetGlobalObject(ctx);
	JSValue handler = qjsw_get_event_handler(ctx, global, NULL,
						  "load", 4);

	if (JS_IsUndefined(handler)) {
		/* Try body element's onload handler */
		exc = dom_html_document_get_body(doc, &body);
		if (exc != DOM_NO_ERR) {
			JS_FreeValue(ctx, global);
			dom_event_unref(evt);
			qjs_leave_thread(thread);
			return true;
		}
		if (body != NULL) {
			JSValue body_val = qjsw_push_node(ctx,
					(struct dom_node *)body);
			handler = qjsw_get_event_handler(ctx, body_val,
					body, "load", 4);
			JS_FreeValue(ctx, body_val);
			dom_node_unref(body);
		}
	}

	if (JS_IsUndefined(handler)) {
		JS_FreeValue(ctx, global);
		dom_event_unref(evt);
		qjs_leave_thread(thread);
		return true;
	}

	/* Call handler with Window as this, event as argument */
	JSValue evt_val = qjsw_push_event(ctx, evt);
	JSValue result = qjsw_pcall(ctx, handler, global, 1, &evt_val, true);
	thread->heap->exec_timing = false;

	JS_FreeValue(ctx, result);
	JS_FreeValue(ctx, evt_val);
	JS_FreeValue(ctx, global);
	JS_FreeValue(ctx, handler);

	js_event_cleanup(thread, evt);
	dom_event_unref(evt);
	qjs_leave_thread(thread);
	return true;
}

bool js_dom_event_add_listener(jsthread *thread,
			       struct dom_document *document,
			       struct dom_node *node,
			       struct dom_string *event_type_dom,
			       void *js_funcval)
{
	(void)thread; (void)document; (void)node;
	(void)event_type_dom; (void)js_funcval;
	return false; /* not yet implemented */
}

void js_handle_new_element(jsthread *thread, struct dom_element *node)
{
	assert(thread);
	assert(node);
	dom_namednodemap *map;
	dom_exception exc;
	dom_ulong idx;
	dom_ulong siz;
	dom_attr *attr = NULL;
	dom_string *key = NULL;
	dom_string *nodename;
	bool is_body = false;

	exc = dom_node_get_node_name(node, &nodename);
	if (exc != DOM_NO_ERR) return;

	if (nodename == corestring_dom_BODY)
		is_body = true;

	dom_string_unref(nodename);

	exc = dom_node_get_attributes(node, &map);
	if (exc != DOM_NO_ERR) return;
	if (map == NULL) return;

	qjs_enter_thread(thread);

	exc = dom_namednodemap_get_length(map, &siz);
	if (exc != DOM_NO_ERR) goto out;

	for (idx = 0; idx < siz; idx++) {
		exc = dom_namednodemap_item(map, idx, &attr);
		if (exc != DOM_NO_ERR) goto out;
		exc = dom_attr_get_name(attr, &key);
		if (exc != DOM_NO_ERR) goto out;
		if (is_body && (
			    key == corestring_dom_onblur ||
			    key == corestring_dom_onerror ||
			    key == corestring_dom_onfocus ||
			    key == corestring_dom_onload ||
			    key == corestring_dom_onresize ||
			    key == corestring_dom_onscroll)) {
			goto skip_register;
		}
		if (dom_string_length(key) > 2) {
			const uint8_t *data =
				(const uint8_t *)dom_string_data(key);
			if (data[0] == 'o' && data[1] == 'n') {
				dom_string *sub = NULL;
				exc = dom_string_substr(
					key, 2, dom_string_length(key),
					&sub);
				if (exc == DOM_NO_ERR) {
					qjsw_register_event_listener_for(
						thread->ctx,
						(struct dom_element *)node,
						sub, false);
					dom_string_unref(sub);
				}
			}
		}
	skip_register:
		dom_string_unref(key); key = NULL;
		dom_node_unref(attr); attr = NULL;
	}

out:
	if (key != NULL)
		dom_string_unref(key);
	if (attr != NULL)
		dom_node_unref(attr);

	dom_namednodemap_unref(map);
	qjs_leave_thread(thread);
}

void js_event_cleanup(jsthread *thread, struct dom_event *evt)
{
	assert(thread);
	qjs_enter_thread(thread);

	JSContext *ctx = thread->ctx;
	JSValue global = JS_GetGlobalObject(ctx);
	JSValue event_map = JS_GetPropertyStr(ctx, global, QJS_EVENT_MAP);

	if (!JS_IsUndefined(event_map) && !JS_IsException(event_map)) {
		/* Delete the event wrapper from the cache using pointer as key */
		char key[32];
		snprintf(key, sizeof(key), "%p", (void *)evt);
		JSAtom atom = JS_NewAtom(ctx, key);
		JS_DeleteProperty(ctx, event_map, atom, 0);
		JS_FreeAtom(ctx, atom);
	}

	JS_FreeValue(ctx, event_map);
	JS_FreeValue(ctx, global);

	qjs_leave_thread(thread);
}

#else /* QJSCORE_TEST_BUILD — stubs for host-native testing */

bool js_fire_event(jsthread *thread, const char *type,
		   struct dom_document *doc, struct dom_node *target)
{
	(void)thread; (void)type; (void)doc; (void)target;
	return true;
}

bool js_dom_event_add_listener(jsthread *thread,
			       struct dom_document *document,
			       struct dom_node *node,
			       struct dom_string *event_type_dom,
			       void *js_funcval)
{
	(void)thread; (void)document; (void)node;
	(void)event_type_dom; (void)js_funcval;
	return false;
}

void js_handle_new_element(jsthread *thread, struct dom_element *node)
{
	(void)thread; (void)node;
}

void js_event_cleanup(jsthread *thread, struct dom_event *evt)
{
	(void)thread; (void)evt;
}

#endif /* QJSCORE_TEST_BUILD */
